# Generated by Django 5.2.8 on 2025-11-30 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(db_column='id_prod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('categoria', models.CharField(blank=True, db_column='categoria', max_length=50, null=True)),
                ('precio_compra', models.DecimalField(blank=True, db_column='precio_compra', decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, db_column='precio_venta', decimal_places=2, max_digits=10, null=True)),
                ('unidad_medida', models.CharField(blank=True, db_column='unidad_medida', max_length=50, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(db_column='id_prov', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=200, null=True)),
                ('rubro', models.CharField(blank=True, db_column='rubro', max_length=80, null=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id_mov', models.AutoField(db_column='id_mov', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], db_column='tipo', max_length=1)),
                ('cantidad', models.IntegerField(db_column='cantidad', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('usuario', models.CharField(blank=True, db_column='usuario', max_length=100, null=True)),
                ('motivo', models.CharField(blank=True, db_column='motivo', max_length=200, null=True)),
                ('id_prod', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.CASCADE, to='appTienda.producto')),
            ],
            options={
                'db_table': 'movimiento_stock',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_prov',
            field=models.ForeignKey(blank=True, db_column='id_prov', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTienda.proveedor'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(db_column='id_stock', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad', default=0)),
                ('ubicacion', models.CharField(blank=True, db_column='ubicacion', max_length=100, null=True)),
                ('stock_minimo', models.IntegerField(db_column='stock_minimo', default=0)),
                ('id_prod', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.CASCADE, to='appTienda.producto')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
